<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>VideoReviewCreator</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>video-review-creator</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
